POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name":"Nityash Kumar",
    "phone": "905808534",
    "address": "jagatpura",
    "company": "squalo solutions",
    "email": "xyz@gmail.com",
    "password": "123456789"
}

###user sign in endpoint

POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "xyz@gmail.com",
    "password": "123456789"
}